services:
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    ports:
      - 3000:3000
    env_file:
      - stack.env
    command:
      - pnpm
      - web
    working_dir: /app
    depends_on:
      prep:
        condition: service_completed_successfully
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    volumes:
      - meilisearch:/meili_data
  workers:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - data:/data
      - ..:/app
    working_dir: /app
    env_file:
      - stack.env
    command:
      - pnpm
      - workers
    depends_on:
      prep:
        condition: service_completed_successfully
  prep:
    build:
      dockerfile: Dockerfile.dev
    working_dir: /app
    env_file:
      - stack.env
    volumes:
      - data:/data
      - ..:/app
    command:
      - /bin/sh
      - -c
      - "pnpm install --frozen-lockfile && pnpm run db:migrate"

volumes:
  meilisearch:
  data:
